-- data analysis 
-- What is the total revenue generated by Olist?
SELECT
    ROUND(SUM(oi.price + oi.freight_value), 2) AS total_revenue
FROM olist_orders o
JOIN olist_order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered';

-- How many orders and customers does Olist have?
SELECT
    COUNT(DISTINCT o.order_id) AS total_orders,
    COUNT(DISTINCT c.customer_unique_id) AS total_customers
FROM olist_orders o
JOIN olist_customers c
    ON o.customer_id = c.customer_id
WHERE o.order_status = 'delivered';

-- How has revenue changed over time?
SELECT
    DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
    ROUND(SUM(oi.price + oi.freight_value), 2) AS revenue
FROM olist_orders o
JOIN olist_order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY 1
ORDER BY 1;

-- Which product categories generate the most revenue?
SELECT
    p.product_category_name,
    ROUND(SUM(oi.price + oi.freight_value), 2) AS revenue
FROM olist_order_items oi
JOIN olist_products p
    ON oi.product_id = p.product_id
JOIN olist_orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY p.product_category_name
ORDER BY revenue DESC
LIMIT 10;

-- Which product categories have the highest demand?
SELECT
    p.product_category_name,
    COUNT(DISTINCT oi.order_id) AS total_orders,
    COUNT(*) AS items_sold
FROM olist_order_items oi
JOIN olist_products p
    ON oi.product_id = p.product_id
JOIN olist_orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY p.product_category_name
ORDER BY total_orders DESC
LIMIT 10;

-- Which Brazilian states generate the most revenue?
SELECT
    c.customer_state,
    ROUND(SUM(oi.price + oi.freight_value), 2) AS revenue
FROM olist_orders o
JOIN olist_customers c
    ON o.customer_id = c.customer_id
JOIN olist_order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY c.customer_state
ORDER BY revenue DESC;

-- What is the Average Order Value?
SELECT
    ROUND(
        SUM(oi.price + oi.freight_value)/ COUNT(DISTINCT o.order_id),2) AS average_order_value
FROM olist_orders o
JOIN olist_order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered';

-- Which payment methods are most commonly used?
SELECT
    payment_type,
    COUNT(*) AS transactions
FROM olist_order_payments
GROUP BY payment_type
ORDER BY transactions DESC;

-- Which payment methods generate the most payment value?
SELECT
    payment_type,
    ROUND(SUM(payment_value), 2) AS total_payment_value
FROM olist_order_payments
GROUP BY payment_type
ORDER BY total_payment_value DESC;

-- Does the number of installments affect order value?
SELECT
    payment_installments,
    COUNT(DISTINCT order_id) AS orders,
    ROUND(AVG(payment_value), 2) AS average_payment_value
FROM olist_order_payments
GROUP BY payment_installments
ORDER BY payment_installments;

-- How long does Olist take to deliver orders?
SELECT
    ROUND(AVG(EXTRACT(DAY FROM(order_delivered_customer_date - order_purchase_timestamp))),2) AS average_delivery_days
FROM olist_orders
WHERE order_status = 'delivered'
  AND order_delivered_customer_date IS NOT NULL;

--How often are orders delivered late?
SELECT
    CASE
        WHEN order_delivered_customer_date
             <= order_estimated_delivery_date
            THEN 'On Time'
        ELSE 'Late'
    END AS delivery_status,
    COUNT(*) AS orders,
    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (),
        2
    ) AS percentage
FROM olist_orders
WHERE order_status = 'delivered'
  AND order_delivered_customer_date IS NOT NULL
  AND order_estimated_delivery_date IS NOT NULL
GROUP BY 1; 

-- Does late delivery affect customer reviews?
SELECT
    CASE
        WHEN o.order_delivered_customer_date
             <= o.order_estimated_delivery_date
            THEN 'On Time'
        ELSE 'Late'
    END AS delivery_status,
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(AVG(r.review_score), 2) AS average_review_score
FROM olist_orders o
JOIN olist_order_reviews r
    ON o.order_id = r.order_id
WHERE o.order_status = 'delivered'
  AND o.order_delivered_customer_date IS NOT NULL
  AND o.order_estimated_delivery_date IS NOT NULL
GROUP BY 1
ORDER BY average_review_score DESC;

-- Which product categories have the best customer ratings?
SELECT
    p.product_category_name,
    COUNT(DISTINCT r.review_id) AS reviews,
    ROUND(AVG(r.review_score), 2) AS average_review_score,
    ROUND(
        SUM(oi.price + oi.freight_value),
        2
    ) AS revenue
FROM olist_order_reviews r
JOIN olist_orders o
    ON r.order_id = o.order_id
JOIN olist_order_items oi
    ON o.order_id = oi.order_id
JOIN olist_products p
    ON oi.product_id = p.product_id
WHERE o.order_status = 'delivered'
  AND p.product_category_name IS NOT NULL
GROUP BY p.product_category_name
HAVING COUNT(DISTINCT r.review_id) >= 50
ORDER BY average_review_score DESC;

-- Who are Olist's most valuable customers?
SELECT
    c.customer_unique_id,
    COUNT(DISTINCT o.order_id) AS frequency,
    ROUND(
        SUM(oi.price + oi.freight_value),
        2
    ) AS monetary,
    MAX(o.order_purchase_timestamp::date) AS last_purchase
FROM olist_orders o
JOIN olist_customers c
    ON o.customer_id = c.customer_id
JOIN olist_order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY c.customer_unique_id
ORDER BY monetary DESC
LIMIT 20;